### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by stefangeneralao** [femosc2/politweet#1]
Hallå, hur installerar man och sånt?! Varför är himlen blå?

**Comment by femosc2** [comment]
Där finns nu en readme där du kan läsa allt om hur man installerar och använder vårt script!

**Comment by kamelpaj** [comment]
Och himlen är blå för att när solljuset passerar genom atmosfären sprids det blå ljuset mer än ljus av andra färger eftersom ljusets spridning ökar med kortare våglängder. När man ser upp mot himlen ser man det ljus som bryts dvs väsentligen blått ljus.
